In [1]:
import pandas as pd
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/sdzheng/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [2]:
df = pd.read_csv("covid19_tweets.csv")

In [3]:
df.head()

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet
0,·èâ·é•‚òª’¨ÍÇÖœÆ,astroworld,wednesday addams as a disney princess keepin i...,2017-05-26 05:46:42,624,950,18775,False,2020-07-25 12:27:21,If I smelled the scent of hand sanitizers toda...,NaN,Twitter for iPhone,False
1,Tom Basile üá∫üá∏,"New York, NY","Husband, Father, Columnist & Commentator. Auth...",2009-04-16 20:06:23,2253,1677,24,True,2020-07-25 12:27:17,Hey @Yankees @YankeesPR and @MLB - wouldn't it...,NaN,Twitter for Android,False
2,Time4fisticuffs,"Pewee Valley, KY",#Christian #Catholic #Conservative #Reagan #Re...,2009-02-28 18:57:41,9275,9525,7254,False,2020-07-25 12:27:14,@diane3443 @wdunlap @realDonaldTrump Trump nev...,['COVID19'],Twitter for Android,False
3,ethel mertz,Stuck in the Middle,#Browns #Indians #ClevelandProud #[]_[] #Cavs ...,2019-03-07 01:45:06,197,987,1488,False,2020-07-25 12:27:10,@brookbanktv The one gift #COVID19 has give me...,['COVID19'],Twitter for iPhone,False
4,DIPR-J&K,Jammu and Kashmir,üñäÔ∏èOfficial Twitter handle of Department of Inf...,2017-02-12 06:45:15,101009,168,101,False,2020-07-25 12:27:08,25 July : Media Bulletin on Novel #CoronaVirus...,"['CoronaVirusUpdates', 'COVID19']",Twitter for Android,False

In [4]:
text_data = df['text'].tolist()

In [5]:
sia = SentimentIntensityAnalyzer()

In [6]:
sentiments = []
for text in text_data:
    sentiment_score = sia.polarity_scores(text)
    sentiment = max(sentiment_score, key=sentiment_score.get)
    sentiments.append(sentiment)

In [7]:
df['sentiment'] = sentiments

In [8]:
df.head()

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet,sentiment
0,·èâ·é•‚òª’¨ÍÇÖœÆ,astroworld,wednesday addams as a disney princess keepin i...,2017-05-26 05:46:42,624,950,18775,False,2020-07-25 12:27:21,If I smelled the scent of hand sanitizers toda...,NaN,Twitter for iPhone,False,neu
1,Tom Basile üá∫üá∏,"New York, NY","Husband, Father, Columnist & Commentator. Auth...",2009-04-16 20:06:23,2253,1677,24,True,2020-07-25 12:27:17,Hey @Yankees @YankeesPR and @MLB - wouldn't it...,NaN,Twitter for Android,False,neu
2,Time4fisticuffs,"Pewee Valley, KY",#Christian #Catholic #Conservative #Reagan #Re...,2009-02-28 18:57:41,9275,9525,7254,False,2020-07-25 12:27:14,@diane3443 @wdunlap @realDonaldTrump Trump nev...,['COVID19'],Twitter for Android,False,neu
3,ethel mertz,Stuck in the Middle,#Browns #Indians #ClevelandProud #[]_[] #Cavs ...,2019-03-07 01:45:06,197,987,1488,False,2020-07-25 12:27:10,@brookbanktv The one gift #COVID19 has give me...,['COVID19'],Twitter for iPhone,False,neu
4,DIPR-J&K,Jammu and Kashmir,üñäÔ∏èOfficial Twitter handle of Department of Inf...,2017-02-12 06:45:15,101009,168,101,False,2020-07-25 12:27:08,25 July : Media Bulletin on Novel #CoronaVirus...,"['CoronaVirusUpdates', 'COVID19']",Twitter for Android,False,neu

In [9]:
df["sentiment"].value_counts()

neu         168635
compound      9987
neg            440
pos             46
Name: sentiment, dtype: int64

In [10]:
sampled_df = df.sample(frac=0.2, random_state=42)
sampled_df

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet,sentiment
20213,British Landlords Association (The BLA),United Kingdom,British Landlords Association -The BLA a FREE ...,2015-07-13 10:44:04,13360,2337,12440,False,2020-07-26 06:55:54,The latest The British Landlord Association Da...,NaN,Paper.li,False,neu
148810,Mo Eco Devo,"Jefferson City, MO",Helping create opportunities for Missourians t...,2009-10-01 18:28:54,4082,531,1360,True,2020-08-18 18:02:45,#COVID19 has affected business owners and work...,"['COVID19', 'MO']",Hootsuite Inc.,False,neu
10763,KYT,"Thane, India","From the house of Thanevaibhav, Thane district...",2016-11-02 16:45:08,239,14,168,False,2020-07-25 05:09:23,July 24: #Thane city #COVID19 update\nNew case...,"['Thane', 'COVID19']",Twitter Web App,False,neu
30395,Dr. Wolfgang H Thome,Germany,"Publisher of ATCNews, Africa's largest publica...",2010-04-20 06:38:31,11759,812,45496,False,2020-07-27 03:03:04,#COVID19\nGlobal overnight developments from 2...,['COVID19'],Twitter Web App,False,neu
69398,Belinda Hayes,Melbourne,Communicating the amazing stories from @monash...,2009-08-27 07:28:18,478,720,217,False,2020-08-04 06:39:22,Theatre can respond to the gendered impacts of...,['COVID19'],Hootsuite Inc.,False,neu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4727,Ritesh,India,Alien stranded on earth. üëΩ,2011-01-23 20:12:35,211,22,2394,False,2020-07-25 09:30:50,Idiotic people and clueless governance is a le...,NaN,Twitter Web App,False,neu
9700,Business Today Kenya,"Nairobi, Kenya","Kenya's No. 1 source of Breaking News, Media U...",2012-02-08 06:54:42,2623,165,42,False,2020-07-25 05:57:35,@emirates will cover customers if they contact...,['COVID19'],Twitter for Android,False,neu
48955,Ander J,"Lagos, Nigeria",trufTalks,2019-03-09 08:28:46,1,16,0,False,2020-07-31 18:00:24,The UK suspends it lock down ease plans follow...,NaN,Socialchief,False,neu
7056,Exante Data,"New York, NY",Data driven insights before the consensus. Ex ...,2016-10-11 20:40:14,7617,349,302,False,2020-07-25 07:55:46,We track how #COVID19 is shutting down economy...,['COVID19'],ExanteData Robots,False,neu
131672,Parduman Kassiedass,"Toronto, Ontario Canada",I am working to get my website and apps built ...,2009-10-29 01:26:06,981,3160,4996,False,2020-08-14 01:59:08,@USlawreview @JillColtonFree I firmly believe ...,"['Covid19', 'Bioweapon', 'Lockdown']",Twitter for Android,False,neu

In [11]:
#!pip install Xformers
from tqdm import tqdm
from transformers import pipeline

text_dataX = sampled_df['text'].tolist()

model_name = "cardiffnlp/twitter-roberta-base-sentiment"

sentiment_classifier = pipeline("sentiment-analysis", model=model_name)

2023-06-01 16:30:14.428677: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-06-01 16:30:14.482836: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-01 16:30:15.375084: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [12]:
sentiment_labels = []
sentiment_scores = []
with tqdm(total=len(text_dataX), desc="Sentiment Analysis") as pbar:
    for text in text_dataX:
        sentiment = sentiment_classifier(text)
        sentiment_labels.append(sentiment[0]['label'])
        sentiment_scores.append(sentiment[0]['score'])
        pbar.update(1)

Sentiment Analysis: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 35822/35822 [3:20:08<00:00,  2.98it/s]

In [13]:
sampled_df['sentiment_X'] = sentiment_labels
sampled_df['scores_X'] = sentiment_scores

In [14]:
sampled_df

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet,sentiment,sentiment_X,scores_X
20213,British Landlords Association (The BLA),United Kingdom,British Landlords Association -The BLA a FREE ...,2015-07-13 10:44:04,13360,2337,12440,False,2020-07-26 06:55:54,The latest The British Landlord Association Da...,NaN,Paper.li,False,neu,LABEL_2,0.694391
148810,Mo Eco Devo,"Jefferson City, MO",Helping create opportunities for Missourians t...,2009-10-01 18:28:54,4082,531,1360,True,2020-08-18 18:02:45,#COVID19 has affected business owners and work...,"['COVID19', 'MO']",Hootsuite Inc.,False,neu,LABEL_1,0.547417
10763,KYT,"Thane, India","From the house of Thanevaibhav, Thane district...",2016-11-02 16:45:08,239,14,168,False,2020-07-25 05:09:23,July 24: #Thane city #COVID19 update\nNew case...,"['Thane', 'COVID19']",Twitter Web App,False,neu,LABEL_1,0.696261
30395,Dr. Wolfgang H Thome,Germany,"Publisher of ATCNews, Africa's largest publica...",2010-04-20 06:38:31,11759,812,45496,False,2020-07-27 03:03:04,#COVID19\nGlobal overnight developments from 2...,['COVID19'],Twitter Web App,False,neu,LABEL_1,0.644444
69398,Belinda Hayes,Melbourne,Communicating the amazing stories from @monash...,2009-08-27 07:28:18,478,720,217,False,2020-08-04 06:39:22,Theatre can respond to the gendered impacts of...,['COVID19'],Hootsuite Inc.,False,neu,LABEL_1,0.754824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4727,Ritesh,India,Alien stranded on earth. üëΩ,2011-01-23 20:12:35,211,22,2394,False,2020-07-25 09:30:50,Idiotic people and clueless governance is a le...,NaN,Twitter Web App,False,neu,LABEL_0,0.935118
9700,Business Today Kenya,"Nairobi, Kenya","Kenya's No. 1 source of Breaking News, Media U...",2012-02-08 06:54:42,2623,165,42,False,2020-07-25 05:57:35,@emirates will cover customers if they contact...,['COVID19'],Twitter for Android,False,neu,LABEL_1,0.885880
48955,Ander J,"Lagos, Nigeria",trufTalks,2019-03-09 08:28:46,1,16,0,False,2020-07-31 18:00:24,The UK suspends it lock down ease plans follow...,NaN,Socialchief,False,neu,LABEL_0,0.507566
7056,Exante Data,"New York, NY",Data driven insights before the consensus. Ex ...,2016-10-11 20:40:14,7617,349,302,False,2020-07-25 07:55:46,We track how #COVID19 is shutting down economy...,['COVID19'],ExanteData Robots,False,neu,LABEL_1,0.668189
131672,Parduman Kassiedass,"Toronto, Ontario Canada",I am working to get my website and apps built ...,2009-10-29 01:26:06,981,3160,4996,False,2020-08-14 01:59:08,@USlawreview @JillColtonFree I firmly believe ...,"['Covid19', 'Bioweapon', 'Lockdown']",Twitter for Android,False,neu,LABEL_1,0.586220

In [15]:
sentiment_classifier(["I hate her"])

[{'label': 'LABEL_0', 'score': 0.9713470935821533}]

In [16]:
sampled_df.to_csv('sampled_df.csv', index=False)